//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHangGitHub.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSVDB : DbContext
    {
        public QLSVDB()
            : base("name=QLSVDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static QLSVDB _instance;
        public static QLSVDB Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new QLSVDB();
                return _instance;
            }
            private set { }
        }
        public virtual DbSet<LopSH> LopSHes { get; set; }
        public virtual DbSet<SV> SVs { get; set; }
    }
}
