//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListUserInAppointment
    {
        public int ListID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> HostID { get; set; }
    
        public virtual Person User { get; set; }
        public virtual Person Host { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
}
